### ISSUE TITLE
Example just results in 400 response

### ISSUE THREAD

**Issue by frankhaugen** [PowerOffice/go-api#11]
By using the example-code, (which has the exact same behaviour by returing 400). The exception thrown is a WebStatusException.

Based on a wild hunch and the namespace of the exception type it has to do with 0Auth, but I can't seem to find some good way to determine what is wrong. Is it access levels, wrong appkey or clientkey, or is there something else going on.

What obvious thing am I missing?

Running code:
```csharp
public class AuthenticationExample
{
    public async Task<Client> AuthenticateAsync(string applicationKey, string clientKey, Settings.EndPointMode endPointMode = Settings.EndPointMode.Demo)
    {
        var authorizationSettings = new AuthorizationSettings
        {
            ApplicationKey = applicationKey,
            ClientKey = clientKey,
            TokenStore = new BasicInMemoryTokenStore(),
            EndPointHost = endPointMode
        };

        try
        {
            var api = await Go.CreateAsync(authorizationSettings);
            var client = api.Client.Get();
            return client;
        }
        catch (Exception e)
        {
            Debugger.Break();
            throw;
        }
    }
}
```

Stacktrace:
```
   at GoApi.Core.OAuth.OAuthClient.<DownloadUri>d__7.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at GoApi.Core.OAuth.OAuthClient.<GetClientAccessToken>d__6.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at GoApi.Core.Authorization.<GetClientAccessToken>d__32.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at GoApi.Core.Authorization.<InitAsync>d__13.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at GoApi.Core.Authorization.<CreateAsync>d__11.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at GoApi.Go.<CreateAsync>d__0.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CompanyName.IntegrationEngine.Plugins.PowerOfficeGo.Examples.AuthenticationExample.<AuthenticateAsync>d__0.MoveNext() in C:\repos\CompanyName.IntegrationEngine\CompanyName.IntegrationEngine.Plugins.PowerOfficeGo\Examples\AuthenticationExample.cs:line 23
```

**Comment by rodfjell** [comment]
Just tested your code snippet here locally on one of my test clients in our demo environment. The code you have works just fine as long as you have a valid applicationkey and clientkey. If I provide an invalid ApplicationKey and/or ClientKey to the method, the same error appears (400). You should take an extra look to see if the keys are correct.

**Comment by frankhaugen** [comment]
> You should take an extra look to see if the keys are correct.
Yes! It was apparently a mixup between production and test, so I was given client key to test and application key to production, when aligning, it worked perfectly.

It would be nice to have had a bit more substance to the reply, like "invalid key(s)", rather than just a 400, but "man tager det man haver".

Tusen takk!  😃
